apiVersion: batch/v1
kind: CronJob
metadata:
  name: k8s-notes-api-cronjob
spec:
  schedule: "* * * * *"  # Run every minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: k8s-notes-api
              image: 19820401/k8s-notes-api:v1
              command:
                - /bin/sh
                - -c
                - echo "Running cron job for k8s-notes-api, at $(date)"
          restartPolicy: OnFailure